
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/Keys/add';
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      API Keys<small>List All</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">API Keys</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                      <?php is_allowed('keys_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="add new Keys (Ctrl+a)" href="<?=  site_url('keys/add'); ?>"><i class="fa fa-plus-square-o" ></i> Add New API Keys</a>
                        <?php }) ?>
                      <?php is_allowed('keys_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export Keys" href="<?= site_url('keys/export'); ?>"><i class="fa fa-file-excel-o" ></i> Export</a>
                        <?php }) ?>
                        <?php is_allowed('keys_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export pdf keys" href="<?= site_url('keys/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> Export PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">API Keys</h3>
                     <h5 class="widget-user-desc">List All API Keys <i class="label bg-yellow"><?= $keys_counts; ?>  items</i></h5>
                  </div>

                  <form name="form_keys" id="form_keys" action="<?= base_url('keys/index'); ?>">
                  
                  <div class="table-responsive">
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Key</th>
                           <th>Is Private Key</th>
                           <th>Ip Addresses</th>
                           <th>Date Created</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_keys">
                     <?php foreach($keyss as $keys): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $keys->id; ?>">
                           </td>
                           <td><?= _ent($keys->key); ?></td> 
                           <td><?= _ent($keys->is_private_key) ? 'yes' : 'no'; ?></td> 
                           <td><?= _ent($keys->ip_addresses); ?></td> 
                           <td><?= _ent($keys->date_created); ?></td> 
                           <td width="200">
                              <?php is_allowed('keys_view', function($option_keys) use ($keys){?>
                              <a href="<?= site_url('keys/view/' . $keys->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> View
                              <?php }) ?>
                              <?php is_allowed('keys_update', function($option_keys) use ($keys){?>
                              <a href="<?= site_url('keys/edit/' . $keys->id); ?>" class="label-default"><i class="fa fa-edit "></i> Update</a>
                              <?php }) ?>
                              <?php is_allowed('keys_delete', function($option_keys) use ($keys){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('keys/delete/' . $keys->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> Remove</a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($keys_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Blog data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="apply bulk actions">Apply</button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="Filter" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value="">All</option>
                            <option <?= $this->input->get('f') == 'key' ? 'selected' :''; ?> value="key">Key</option>
                           <option <?= $this->input->get('f') == 'level' ? 'selected' :''; ?> value="level">Level</option>
                           <option <?= $this->input->get('f') == 'ignore_limits' ? 'selected' :''; ?> value="ignore_limits">Ignore Limits</option>
                           <option <?= $this->input->get('f') == 'is_private_key' ? 'selected' :''; ?> value="is_private_key">Is Private Key</option>
                           <option <?= $this->input->get('f') == 'ip_addresses' ? 'selected' :''; ?> value="ip_addresses">Ip Addresses</option>
                           <option <?= $this->input->get('f') == 'date_created' ? 'selected' :''; ?> value="date_created">Date Created</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="filter search">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('keys');?>" title="reset filters">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script type="text/javascript" src="<?= BASE_ASSET; ?>/jquery-clipboard"></script>
<script>
  $(document).ready(function() {
    $('.remove-data').click(function() {

        var url = $(this).attr('data-href');

        swal({
                title: "Are you sure?",
                text: "data to be deleted can not be restored!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                cancelButtonText: "No, cancel plx!",
                closeOnConfirm: true,
                closeOnCancel: true
            },
            function(isConfirm) {
                if (isConfirm) {
                    document.location.href = url;
                }
            });

        return false;
    });


    $('#apply').click(function() {

        var bulk = $('#bulk');
        var serialize_bulk = $('#form_keys').serialize();

        if (bulk.val() == 'delete') {
            swal({
                    title: "Are you sure?",
                    text: "data to be deleted can not be restored!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel plx!",
                    closeOnConfirm: true,
                    closeOnCancel: true
                },
                function(isConfirm) {
                    if (isConfirm) {
                        document.location.href = BASE_URL + '/keys/delete?' + serialize_bulk;
                    }
                });

            return false;

        } else if (bulk.val() == '') {
            swal({
                title: "Upss",
                text: "Please choose bulk action first!",
                type: "warning",
                showCancelButton: false,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Okay!",
                closeOnConfirm: true,
                closeOnCancel: true
            });

            return false;
        }

        return false;

    }); /*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event) {
        if (checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

}); /*end doc ready*/
</script>