<link rel="stylesheet" href="<?= BASE_ASSET; ?>jquery-switch-button/jquery.switchButton.css">
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/user/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Pengguna
      <small>Daftar Pengguna</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Pengguna</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-primary">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('user_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="Tambah pengguna baru (Ctrl+A)" href="<?= site_url('user/add'); ?>"><i class="fa fa-plus-square-o" ></i> Tambah Pengguna Baru</a>
                        <?php }) ?>
                        <?php is_allowed('user_export', function(){?>
                        <a class="btn btn-flat btn-success" title="Export pengguna dalam format XLS" href="<?= site_url('user/export'); ?>"><i class="fa fa-file-excel-o" ></i> Export XLS</a>
                        <?php }) ?>
                        <?php is_allowed('user_export', function(){?>
                        <a class="btn btn-flat btn-success" title="Export pengguna dalam format PDF" href="<?= site_url('user/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> Export PDF</a>
                        <?php }) ?>

                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Pengguna</h3>
                     <h5 class="widget-user-desc">Daftar Semua Pengguna</h5>
                     <h5 class="widget-user-desc">Total : <i class="label bg-blue"><?= $user_counts; ?>  Pengguna</i></h5>
                  </div>

                  <form name="form_user" id="form_user" action="<?= base_url('user/index'); ?>">
                  
                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Nama Penguna</th>
                           <th>Username</th>
                           <th>Status</th>
                           <th>Aksi</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_user">
                     <?php foreach($users as $user): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $user->id; ?>">
                           </td>
                           <td>

                              <div class="chip">
                                <?php if (is_file(FCPATH . 'uploads/user/' . $user->avatar)): ?>
                                <?php $img_url = BASE_URL . 'uploads/user/' . $user->avatar; ?>
                                <?php else: ?>
                                <?php $img_url = BASE_URL . 'uploads/user/yuuki0.webp'; ?>
                                <?php endif; ?>
                                <a class="fancybox" rel="group" href="<?= $img_url; ?>">
                                  <img src="<?= $img_url; ?>" alt="Person" width="50" height="50">
                                </a>
                                <?= _ent($user->full_name); ?>
                              </div>
                           </td>
                           <td><?= _ent($user->username); ?></td>
                           <td>
                              
                           <input type="checkbox" name="status" data-user-id="<?= $user->id; ?>" class="switch-button" <?= $user->banned ?:'checked'; ?> >
                           </td>
                           <td width="200">
                              <?php is_allowed('user_view', function($option_user) use ($user){?>
                                <a href="<?= site_url('user/view/' . $user->id); ?>" class="label-default"><i class="fa  fa-newspaper-o "></i> Lihat</a>
                              <?php }) ?>
                              <?php is_allowed('user_update', function($option_user) use ($user){?>
                              <a href="<?= site_url('user/edit/' . $user->id); ?>" class="label-default"><i class="fa fa-edit "></i> Edit</a>
                              <?php }) ?>
                              <?php is_allowed('user_delete', function($option_user) use ($user){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('user/delete/' . $user->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> Hapus</a>
                              <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($user_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Data pengguna tidak tersedia :(
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="" selected="true" disabled>Aksi Cepat</option>
                           <option value="delete">Hapus</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat"  name="apply" id="apply" value="Apply" title="Terapkan aksi">Terapkan</button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="Filter" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value="">Semua</option>
                           <option <?= $this->input->get('f') == 'id' ? 'selected' :''; ?> value="id">ID</option>
                           <option <?= $this->input->get('f') == 'username' ? 'selected' :''; ?> value="username">Username</option>
                           <option <?= $this->input->get('f') == 'full_name' ? 'selected' :''; ?> value="full_name">Nama Lengkap</option>
                           <option <?= $this->input->get('f') == 'email' ? 'selected' :''; ?> value="email">Email</option>
                        </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="filter pencarian">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('user'); ?>" title="reset filter">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  <?= form_close(); ?>
                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function() {
    $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
        checkboxClass: 'icheckbox_flat-green',
        radioClass: 'iradio_flat-green'
    });

    $('.switch-button').switchButton({
        labels_placement: 'right',
        on_label: 'Aktif',
        off_label: 'NonAktif'
    });

    $(document).on('change', 'input.switch-button', function() {
        var status = 'inactive';
        var id = $(this).attr('data-user-id');
        var data = [];

        if ($(this).prop('checked')) {
            status = 'active';
        }

        data.push({
            name: csrf,
            value: token
        });
        data.push({
            name: 'status',
            value: status
        });
        data.push({
            name: 'id',
            value: id
        });

        $.ajax({
                url: BASE_URL + '/user/set_status',
                type: 'POST',
                dataType: 'JSON',
                data: data,
            })
            .done(function(data) {
                if (data.success) {
                    toastr['success'](data.message);
                } else {
                    toastr['warning'](data.message);
                }

            })
            .fail(function() {
                toastr['error']('Error update status');
            });
    });

    $('.remove-data').click(function() {
        var url = $(this).attr('data-href');

        swal({
                title: "Hapus pengguna ini?",
                text: "Data pengguna yang sudah dihapus, tidak dapat dikembalikan lagi!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Hapus",
                cancelButtonText: "Batal",
                closeOnConfirm: true,
                closeOnCancel: true
            },
            function(isConfirm) {
                if (isConfirm) {
                    document.location.href = url;
                }
            });

        return false;
    });

    $('#apply').click(function() {

        var bulk = $('#bulk');
        var serialize_bulk = $('#form_user').serialize();

        if (bulk.val() == 'delete') {

            <?php if ($this->aauth->is_allowed('user_delete')): ?>
                swal({
                        title: "Hapus pengguna yang dipilih?",
                        text: "Data pengguna yang sudah dihapus, tidak dapat dikembalikan lagi!",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "Konfirmasi, Hapus",
                        cancelButtonText: "Batalkan",
                        closeOnConfirm: true,
                        closeOnCancel: true
                    },
                    function(isConfirm) {
                        if (isConfirm) {
                            document.location.href = BASE_URL + '/user/delete?' + serialize_bulk;
                        }
                    }); <?php endif; ?>

            return false;

        } else if (bulk.val() == '') {
            swal({
                title: "Upss",
                text: "Pilih aksi yang diinginkan terlebih dahulu!",
                type: "warning",
                showCancelButton: false,
                confirmButtonColor: "#5595DD",
                confirmButtonText: "Oke",
                closeOnConfirm: true,
                closeOnCancel: true
            });

            return false;
        }

        return false;

    }); /*end appliy click*/

    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event) {
        if (checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

}); /*end doc ready*/
</script>