
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Pengajuan Pinjam Barang      <small>Detail Pengajuan Pinjam Barang</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('form_pengajuan_pinjam_barang'); ?>">Pengajuan Pinjam Barang</a></li>
      <li class="active">Detail</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Pengajuan Pinjam Barang</h3>
                     <h5 class="widget-user-desc">Detail Pengajuan Pinjam Barang</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_form_pengajuan_pinjam_barang" id="form_form_pengajuan_pinjam_barang" >
                   
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">NIK/NIDN/NIM </label>

                        <div class="col-sm-8">
                           <?= _ent($form_pengajuan_pinjam_barang->nik_nidn_nim); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Nama Peminjam </label>

                        <div class="col-sm-8">
                           <?= _ent($form_pengajuan_pinjam_barang->nama_peminjam); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">No Telp / Hp </label>

                        <div class="col-sm-8">
                           <?= _ent($form_pengajuan_pinjam_barang->no_telp_hp); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Nama Barang </label>

                        <div class="col-sm-8">
                           <?= _ent($form_pengajuan_pinjam_barang->nama_barang); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Dipakai Di </label>

                        <div class="col-sm-8">
                           <?= _ent($form_pengajuan_pinjam_barang->dipakai_di); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Digunakan Untuk </label>

                        <div class="col-sm-8">
                           <?= _ent($form_pengajuan_pinjam_barang->digunakan_untuk); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Jumlah </label>

                        <div class="col-sm-8">
                           <?= _ent($form_pengajuan_pinjam_barang->jumlah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Tanggal Pinjam </label>

                        <div class="col-sm-8">
                           <?= _ent($form_pengajuan_pinjam_barang->tanggal_pinjam); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group option">               
                  <label for="content" class="col-sm-2 control-label">Tanggal Kembali </label>

                        <div class="col-sm-8">
                           <?= _ent($form_pengajuan_pinjam_barang->tanggal_kembali); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('form_pengajuan_pinjam_barang_update', function($option_form_pengajuan_pinjam_barang) use ($form_pengajuan_pinjam_barang){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit form_pengajuan_pinjam_barang (Ctrl+e)" href="<?= site_url('form_pengajuan_pinjam_barang/edit/'.$form_pengajuan_pinjam_barang->id); ?>"><i class="fa fa-edit" ></i> Edit Form Pengajuan Pinjam Barang</a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('form_pengajuan_pinjam_barang/'); ?>"><i class="fa fa-undo" ></i> Go Form Pengajuan Pinjam Barang List</a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
